### ISSUE TITLE
Feature Request - User ruamel.yaml to decrease the diff when updating YML files

### ISSUE THREAD

**Issue by b-per** [Montreal-Analytics/dbt-gloss#125]
**Describe the feature you'd like**

The hook `unify-column-description` generates big diffs, even for changing just one column, as it defaults to the YML format

```
models:
- name: orders
  description: This table has basic information...
```

when most of the code from the dbt docs follow the convention of indentation 

```
models:
  - name: orders
    description: This table has basic information...
```

`ruamel.yaml` is an alternative to PyYAML that supports "round trip" YAML loading/dumping to limit those changes

**Additional context**

Happy to work on it, I have a local version working

**Comment by BAntonellini** [comment]
Hey @b-per, thank you for your contribution. We don't find this Issue as a priority right now, and will close as part of the reconditioning dbt-checkpoint is receiving. 

Will appreciate, as you mentioned to be `happy to work on it`, if you can directly open a PR. We'll be glad to review your proposals.

On second thought. Since this an action that changes the contents of a file, it might be better suited to [dbt-coves](https://github.com/datacoves/dbt-coves).  There are also other libraries that accomplish this. We want to keep checkpoint to hooks that validate the dbt project vs modifying it.
